### PR TITLE
[BUGFIX] Temporary file deletion on iOS

### PR DESCRIPTION
**Pull request by lagmoellertim**
Deleting the whole temporary directory caused an error on iOS since that path is protected by the OS. So instead of deleting the directory itself, the contained files and folders inside the temporary directory are now deleted, fixing the bug on iOS.

### CODE REVIEW

**Comment by astubenbord** [comment]
Thanks, I'll check it out this afternoon. Just out of interest, do you use this app on iOS?

**Comment by lagmoellertim** [comment]
I discovered your app yesterday and since the other Paperless app is rather outdated and missing many features and the web ui is harder to navigate on mobile, I decided to build it for my iPad. After fixing this minor bug, everything seems to work perfectly.

**Comment by astubenbord** [comment]
Very cool!

**Comment by tarunkumar519** [comment]
Will someone be able to host or send the built ipa file for iOS or include it in the releases? Btw This looks like an awesome project and im sure this will be a big thing for open source since no other good tools like paperless exist and app on android already looks excellent ! Looking forward to iOS release( only if possible by contributors) or ipa releases

**Comment by astubenbord** [comment]
I can also build for ios and include the files in the reelases, but I don't have an apple developer account. Sorry for the wait on the pull requests btw, I want to merge these into the new version, should be done this weekend.

**Review by astubenbord — APPROVED** [review]
I commented out the line you said threw the error on iOS in the latest release. Just replace it with your implementation. Thanks

**Pull request merged**
