### PR TITLE
Czech translation created

### PR DESCRIPTION
**Pull request by svetlemodry**
Czech translation created

### CODE REVIEW

**Comment by astubenbord** [comment]
Thanks a lot! I'll take a look and merge it later :)

**Review by astubenbord — APPROVED** [review]

**Comment by astubenbord** [comment]
Hi, if you'd be interested I could invite you to the Localizely project. If you don't know what it is, it is an online platform to manage translations. I'd appreciate it very much :)

**Comment by svetlemodry** [comment]
Yeah, gladly. I saw the mention about Localizely after I was done with the text file. Sorry if it was more work for you to merge!
I use Transifex/Crowdin/Weblate for some other projects, so I believe this will be pretty similar.

**Comment by svetlemodry** [comment]
@astubenbord Got myself an account on Localizely. Not sure if/how you can find me there and invite me. I am there under the same nickname as here.
Hope I won't have to pay the fee there after the 14 days trial .)

**Comment by astubenbord** [comment]
Sorry for the late reply, I'll need the email you used to sign up with. You can just send me a mail to paperless-mobile@protonmail.com :)

**Comment by svetlemodry** [comment]
@astubenbord, invite worked, thanks!
Although it still shows me I am on a trial that'll end in 10 days. Don't think I'll be able to afford to stay there for $19/month even for the starter pack they offer.

**Comment by astubenbord** [comment]
The way I understood it is that you get all benefits for the first 15 days and then you will automatically be downgraded to the free model, where only 250 keys can be stored. My account will also run out in a couple of days, I'll report back to you once I know that for certain. They also have an open source program which would allow us to have the 'pro' version for free. I'll apply for that and let you know!

**Comment by svetlemodry** [comment]
Okido, let's see how it behaves once the trial expires then!

**Comment by astubenbord** [comment]
I already received feedback from their support and we are eligible for the open source free plan and it was already assigned to my account! I think once your trial runs you can still use your account with this project with all premium features because the project is hosted with this account and not yours

**Pull request merged**
