### PR TITLE
Translate to French - EDIT : MOVED TO CROWDIN

### PR DESCRIPTION
**Pull request by SpicyWasab**
Hi !

I noticed that the French translation was incomplete. I don't know if you accept translations pull requests but I translated near everything that wasn't.

For some strings, I had to consider the case when it's plural (doesn't really matter in English but does in French). e.g. : "{count} selected", "{count} sélectionné(s)" (l. 236)

I also left some strings in English because I wasn't sure about the exact translation, or about the exact context the string is displayed in. Here's the list of non-translated strings :
```jsonc
"couldNotAcknowledgeTasks": "Could not acknowledge tasks.", // 261
"anErrorOccurredRemovingTheScans": "An error occurred removing the scans.", // 309
"allSeen": "All seen", // 433
"anyAssigned": "Any assigned", // 459
"match": "Match", // 467
"notAssigned": "Not assigned", // 471
"clearAll": "Clear all", // 603
```
There's two translations I'm not really sure about :
```jsonc
"caseIrrelevant": "Insensible à la casse", // 463
```
- I translated this one as if it was "case insensitive". I also just looked up the german translation, apparently it should be that. I just never encountered/heard "case irrelevant" before.

```jsonc
"report": "RAPPORT", // 329
```
- Not sure about this one. Looked up the german version, but still not sure. Translated it as if it was "report" from "crash report", but it could also be "signaler" as well (like when you _report_ a bug).

I was also wondering why some "zero{}" are empty, while others are filled with the plural form ? Like this :
```jsonc
"days": "{count, plural, zero{days} one{day} other{days}}", // 251
```
- filled with 'days', plural
```jsonc
"months": "{count, plural, zero{} one{month} other{months}}", // 381
```
- empty

I have some concerns about some translations as well.  French tends to be more verbose than English most of the time, so I'm wondering if some strings are too long to be displayed properly / nicely on the UI ...

PS : It doesn't really matter, but I just noticed an error there :
```jsonc
"mangeFilesAndStorageSpace": "Gérer les fichiers et l'espace de stockage", // 635
"@mangeFilesAndStorageSpace": {}, // 636
```
Where "manage" was misstyped to "mange" (?). It doesn't matter, I just found that funny.

Feel free to let me know if there's anything to change !

### CODE REVIEW

**Comment by SpicyWasab** [comment]
Alright, I did that very late in the night (when it's late I tend to be more productive and also do things without thinking a lot about it)
I didn't notice the crowdin project, I'm gonna move that to crowdin, I think it's just a matter of copy-pasting the whole document.

**Comment by SpicyWasab** [comment]
Okay, I moved the translated strings to Crowdin, it was pretty fast to do.
I'll definitely translate directly in Crowdin the next time, it seems waaayyyyy better to do ^^'

"Translated to 97%"

**Comment by astubenbord** [comment]
Thanks! :) I'll close this request and merge the changes into development, I'll push a new version soon

**Comment by astubenbord** [comment]
@SpicyWasab I've also added context information to the missing translations, maybe that helps, if you have any more questions feel free to @ me :)

**Comment by SpicyWasab** [comment]
@astubenbord Yeah thanks, that helped a lot !

I also looked up some translations in the Paperless web client when I was unsure, and also to be sure it was the best. (like for some algorithms)
For the "Extended : Label for the extended query option" I assumed it was the same as "Advanced search", so I translated it to "Recherche avancée".

I'm still unsure about the "Could not acknowledge tasks." one though ...

> Yes, it's a typo, you're not supposed to eat the files smile
Sorry but since english isn't my native language I'm just wondering why you're using the verb "eat. ^^'
I got the general idea though. I just found that funny to report xD

> This is because the "zero" translations are never used in reality, but I see your point, maybe it makes sense to also translate them for consistency
Yup, I know it's unused, I still translated them anyway. I just found it was weird that some were completed, and others left empty ...
Doesn't matter anyways c:


The good news is : french is currently 99% translated :) There's just the "acknowledge task" thing leaving.
I still have some concerns about some of my translations being too long and verbose, so I think I'm gonna do a review of everything in the app when it's merged.

**Comment by astubenbord** [comment]
Great, nice to have another language fully completed.

When uploading files, paperless keeps track of the consumption of files in so called tasks. A task for instance resembles the activity of performing OCR on a document. Once a file hast been successfully consumed, this task is added to the "successful" group. These tasks are then basically marked as unseen until they are acknowledged (I. e. the user has seen that a task was successful/has failed etc.).

I'm not 100 percent if and where this is used. However, that is the context, maybe this helps?

**Comment by SpicyWasab** [comment]
Yeah, that's nice !

I see, thanks.
I don't 
I used Github's search feature to see where it was used.
Apparenttly

**Comment by SpicyWasab** [comment]
@astubenbord Yeah, that's cool  !

I see, thanks. It's basically what is displayed in the paperless web client.
I may be wrong, but I don't think there's any task list in the app yet :thinking: I tried to search on Github where the error message was used, and apparently it's only used in the "acknowledgeTask()" function, which doesn't seem to be called anywhere (https://github.com/astubenbord/paperless-mobile/search?q=acknowledgeTasks), so I definitely think it's not used yet.

Anyways, it doesn't really matter because it's translated c:
I wrote "Impossible de marquer la tâche comme vue.", which translates to "Could not mark task as seen.".
In the web client it's not "acknowledge", but "dismiss" or "ignorer" in french ("ignore"), but I wasn't really fond of "Could not ignore task", sounds weird imo xD

So ... it's now translated to 100% c: Any ETA of the translations being released in a future app ? It's not urgent at all, I just would like to know when I could see them in-app to apply some corrections.

**Comment by astubenbord** [comment]
I'll try to do it tomorrow, but not sure if I find the time.

**Comment by astubenbord** [comment]
Sorry for the wait, the new update should be up by now.

**Pull request closed without merging**
